name: Publish in GitHub Package Registry

on:  
  push:
    tags:
      - '*'

jobs:  
  job2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Zip Folder
      run: zip -r ${{ github.event.repository.name }}.zip . -x ".git/*" ".github/*" "composer.json" "composer.lock" ".gitignore"

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ github.event.repository.name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}