name: Publish in GitHub Package Registry

on:  
  push:
    tags:
      - '*'

jobs:  
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Upload app to Nextcloud appstore
          uses: R0Wi/nextcloud-appstore-push-action@v1
          with:
            app_name: ${{ env.APP_NAME }}
            appstore_token: ${{ secrets.APPSTORE_TOKEN }}
            download_url: ${{ steps.attach_to_release.outputs.browser_download_url }}
            app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
            nightly: ${{ github.event.release.prerelease }}